# build.yml
# checks and test build on push and pull request to master branch
name: build

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          yarn install

      - name: Code Format checks
        run: |
          yarn run prettier:check

      - name: Build
        run: |
          yarn run build
        env:
          CI: true